"""add occasions table

Revision ID: f626ead1bfd0
Revises: 005
Create Date: 2025-12-13 10:04:03.796923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f626ead1bfd0'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occasions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('seo_title', sa.String(length=60), nullable=True),
    sa.Column('seo_description', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_occasions_active_order', 'occasions', ['is_active', 'display_order'], unique=False)
    op.create_index('idx_occasions_slug', 'occasions', ['slug'], unique=False)
    op.create_table('redirects',
    sa.Column('old_path', sa.String(length=500), nullable=False, comment='URL antiga (sem dominio)'),
    sa.Column('new_path', sa.String(length=500), nullable=False, comment='URL nova (com / inicial)'),
    sa.Column('is_pattern', sa.Boolean(), nullable=False, comment='Se True, old_path e prefixo para match parcial'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Se o redirect esta ativo'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='Contador de uso do redirect'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redirects_is_active'), 'redirects', ['is_active'], unique=False)
    op.create_index(op.f('ix_redirects_old_path'), 'redirects', ['old_path'], unique=True)
    op.alter_column('newsletter_signups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('post_products', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('posts', 'status',
               existing_type=postgresql.ENUM('draft', 'review', 'scheduled', 'published', 'archived', name='post_status'),
               nullable=False)
    op.alter_column('posts', 'shared',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('posts', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_posts_fulltext', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_tags_gin', table_name='posts', postgresql_using='gin')
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'BRL'::character varying"))
    op.alter_column('products', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'availability',
               existing_type=postgresql.ENUM('available', 'unavailable', 'unknown', name='product_availability'),
               nullable=False)
    op.alter_column('products', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'internal_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('products', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_products_categories_gin', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_fulltext', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_tags_gin', table_name='products', postgresql_using='gin')
    op.alter_column('sessions', 'device_type',
               existing_type=postgresql.ENUM('mobile', 'desktop', 'tablet', 'unknown', name='device_type'),
               nullable=False)
    op.alter_column('sessions', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'is_new_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('sessions', 'device_type',
               existing_type=postgresql.ENUM('mobile', 'desktop', 'tablet', 'unknown', name='device_type'),
               nullable=True)
    op.create_index('ix_products_tags_gin', 'products', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_fulltext', 'products', [sa.text("to_tsvector('portuguese'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(short_description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('ix_products_categories_gin', 'products', ['categories'], unique=False, postgresql_using='gin')
    op.alter_column('products', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'internal_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('products', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'availability',
               existing_type=postgresql.ENUM('available', 'unavailable', 'unknown', name='product_availability'),
               nullable=True)
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'BRL'::character varying"))
    op.create_index('ix_posts_tags_gin', 'posts', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_fulltext', 'posts', [sa.text("to_tsvector('portuguese'::regconfig, (((((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(subtitle, ''::character varying)::text) || ' '::text) || COALESCE(content, ''::text)) || ' '::text) || COALESCE(seo_focus_keyword, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.alter_column('posts', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('posts', 'shared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'status',
               existing_type=postgresql.ENUM('draft', 'review', 'scheduled', 'published', 'archived', name='post_status'),
               nullable=True)
    op.alter_column('posts', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('post_products', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('newsletter_signups', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_redirects_old_path'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_is_active'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index('idx_occasions_slug', table_name='occasions')
    op.drop_index('idx_occasions_active_order', table_name='occasions')
    op.drop_table('occasions')
    # ### end Alembic commands ###
