"""add_content_and_next_review_to_occasions

Revision ID: 7d02c38a81cd
Revises: f626ead1bfd0
Create Date: 2025-12-13 21:53:50.442381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d02c38a81cd'
down_revision: Union[str, None] = 'f626ead1bfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occasions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('occasions', sa.Column('next_review_date', sa.Date(), nullable=True))
    op.create_index('idx_occasions_next_review', 'occasions', ['next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_occasions_next_review', table_name='occasions')
    op.drop_column('occasions', 'next_review_date')
    op.drop_column('occasions', 'content')
    # ### end Alembic commands ###
